### ISSUE TITLE
Chapter06 - Button Background Color Animation

### ISSUE THREAD

**Issue by Ticrabe** [PacktPublishing/Mastering-GUI-Programming-with-Python#1]
Chapter06 -  file "game_lobby.py"
When executed, the animation "bg_color_animation" is not working.
Only the text of the "submit" button is changing, not its background as expected.

[game_lobby.zip](https://github.com/PacktPublishing/Mastering-GUI-Programming-with-Python/files/3873520/game_lobby.zip)

**Comment by alandmoore** [comment]
It is working here for me.  What platform and version of Python & PyQt are you using?

**Comment by Ticrabe** [comment]
Hi,
I am on  a Windows 10/ Python 3.7.2 / PyQt5 5.12 configuration
I have tested with PyQt5 5.12.1 & PyQT5 5.13.2, same results.
I continue my investigations ;)
