### ISSUE TITLE
Should ch2 calendar_form.py grid layout have zero-based indexing?

### ISSUE THREAD

**Issue by cortical-iv** [PacktPublishing/Mastering-GUI-Programming-with-Python#11]
In `calendar_form.py` the grid indexing is one-based, while my understanding (and as stated in the book on pages 38-9) of the convention for `QGridLayout` is to use 0-based indexing. So I think the code here:
https://github.com/PacktPublishing/Mastering-GUI-Programming-with-Python/blob/master/Chapter02/calendar_form.py#L61

Should probably be revised to be zero-based:
```
        event_form_layout.addWidget(self.event_title, 0, 0, 1, 3)
        event_form_layout.addWidget(self.event_category, 1, 0)
        event_form_layout.addWidget(self.event_time, 1, 1,)
        event_form_layout.addWidget(self.allday_check, 1, 2)
        event_form_layout.addWidget(self.event_detail, 2, 0, 1, 3)
        event_form_layout.addWidget(self.add_button, 3, 1)
        event_form_layout.addWidget(self.del_button, 3, 2)
```

What is impressive is it works both ways!

**Comment by alandmoore** [comment]
It will work fine either way; the empty rows will simply collapse to no space.  Sometimes it's useful to skip rows in case you want to add things later.

We will leave this for now to minimize confusion for readers downloading the code and comparing it to the book.
