### ISSUE TITLE
Ch 3: self.destroy in CategoryWindow hangs app, self.close works

### ISSUE THREAD

**Issue by cortical-iv** [PacktPublishing/Mastering-GUI-Programming-with-Python#12]
With the following line the new category widget causes my app to hang when I press cancel:
```
        self.cancel_btn = qtw.QPushButton('Cancel',
                                          clicked=self.destroy)
```
This is from `calendar_app.py`: 
https://github.com/PacktPublishing/Mastering-GUI-Programming-with-Python/blob/master/Chapter03/calendar_app.py#L30

When I change `destroy` to `close` it works fine. I also just noticed in the book it has `close` (p 76), so probably just a version glitch. :)

**Comment by cortical-iv** [comment]
Note this is also an issue in the text_editor for Chapter 4 for the quit_action:
https://github.com/PacktPublishing/Mastering-GUI-Programming-with-Python/blob/master/Chapter04/text_editor.py#L97

**Comment by alandmoore** [comment]
Thanks for reporting this!
