### ISSUE TITLE
Ch 5 remove_rows: when N items in one row are selected, it removes N rows

### ISSUE THREAD

**Issue by EricThomson** [PacktPublishing/Mastering-GUI-Programming-with-Python#13]
I was playing with the code for csv_editor, and noted when I tried to remove a row when I had multiple items selected in that row, it removed the same number of rows as selected items. This is because it uses `len(selected)` to pick how many rows to remove (instead of number of rows). I changed it to instead find out how many _rows_ are selected (in `MainWindow`):

```
        num_rows = len(set(index.row() for index in selected))
        if selected:
            self.model.removeRows(selected[0].row(), num_rows, None)
```

And now `remove_rows` works as desired.

**Comment by alandmoore** [comment]
Thanks for posting this.  I've added a fix to the code, and I believe there is an errata for the book on this.
