### ISSUE TITLE
Ch 4: Save file error message fails

### ISSUE THREAD

**Issue by btuftin** [PacktPublishing/Mastering-GUI-Programming-with-Python#14]
The call to `qtw.QMessageBox.critical(f"Could not open file: {e}")` fails with error 
`TypeError: critical(QWidget, str, str, buttons: Union[QMessageBox.StandardButtons,
QMessageBox.StandardButton] = QMessageBox.Ok, defaultButton: QMessageBox.StandardButton = QMessageBox.NoButton): not enough arguments`

`critical` requires a reference to parent and a title, so this works:
`qtw.QMessageBox.critical(self, "Error", f"Could not load file: {e}")`

**Comment by alandmoore** [comment]
Thanks for reporting this.  Fixed by 565b8e3
