### ISSUE TITLE
coffee_list1_py

### ISSUE THREAD

**Issue by jekadwell** [PacktPublishing/Mastering-GUI-Programming-with-Python#2]
I am getting the below when I run the program.
Print the name of the function = (get_id_for_row)
print the value of 'index' =  <PyQt5.QtCore.QModelIndex object at 0x000001E71EB24A58>

Below is the function from the code in GitHub: ( I added the print statements )
    def get_id_for_row(self, index):
        print("(get_id_for_row)")
        print('index = ', index)
        index = index.siblingAtColumn(0)

        coffee_id = self.coffee_list.model().data(index)
        print('coffee_id = ', coffee_id)
        return coffee_id
Can you provide assistance in resolving this issue?  
Thanks,
John K

**Comment by alandmoore** [comment]
What is the actual issue here?  Was this one of the issues resolved by updating PyQt?

**Comment by alandmoore** [comment]
I'm assuming this is part of what was fixed with your PyQt5 upgrade. Feel free to reopen if not.
