### ISSUE TITLE
Reviews

### ISSUE THREAD

**Issue by jekadwell** [PacktPublishing/Mastering-GUI-Programming-with-Python#3]
The program does not show the reviews.  I cannot locate the reason why this is happening.
Any assistance would be appreciated.
Thanks.
 def show_coffee(self, coffee_index):
        print('coffee_index ', coffee_index)
        self.mapper.setCurrentIndex(coffee_index.row())
        print('coffee_index.row() ', coffee_index.row())
        print("Hello")
The below print statement does not print.  The program stops after printing the above "Hello".

        print('coffee_index.siblingAtColumn(0) ', coffee_index.siblingAtColumn(0))
        # show the reviews
The reviews never show up after doubleclicking.

        id_index = coffee_index.siblingAtColumn(0)
        print('index_id ', id_index, 'coffee_index ', coffee_index)

        self.coffee_id = int(self.coffees_model.data(id_index))
        self.reviews.model().setFilter(f'coffee_id = {self.coffee_id}')
        self.reviews.model().setSort(3, qtc.Qt.DescendingOrder)
        self.reviews.model().select()
        self.reviews.resizeRowsToContents()
        self.reviews.resizeColumnsToContents()

**Comment by alandmoore** [comment]
Was this the issue resolved by updating PyQt5?

**Comment by jekadwell** [comment]
Mr. Moore,

Thanks for getting back to me.  When I ran the example, and double clicked on a ‘coffee’, the program would end.  I would not see the reviews.

After updating PyQt5 using pip the program worked fine.

Thanks,

John Kadwell
