### ISSUE TITLE
coffee_list2.py error

### ISSUE THREAD

**Issue by jekadwell** [PacktPublishing/Mastering-GUI-Programming-with-Python#4]
I discovered the cause for the problem.
I was using an Anaconda Environment that used version 5.9.2 for PyQt5.
I followed the instructions at the front of the book 
(PyQt 5.12, 
which you can install from the Python Package Index using this command: 
$ pip install --user PyQt5)

and installed PyQt5 Version  5.14.0 and the program worked.

**Comment by alandmoore** [comment]
Was this the cause of both your errors, or one in particular?
Sorry I haven't responded sooner, have been busy with work and holiday activities.
