### ISSUE TITLE
Quit program code in Chapter 4 text_editor.py line 97

### ISSUE THREAD

**Issue by jekadwell** [PacktPublishing/Mastering-GUI-Programming-with-Python#6]
#quit_action = file_menu.addAction('Quit', self.destroy)
        quit_action = file_menu.addAction('Quit')
        quit_action.triggered.connect(self.exitProg)

    def exitProg(self):
        sys.exit()

Line 97 of of the the code is what I have commented out in the above.  When I run this code using PyCharm, it does not actually end the program.  The window is closed, but the program continues to run.  I changed to code to the above to actually get it program to end.  

I just wanted to point this out as I don't know if it not closing the program is a PyCharm issue or if I am misinterpreting what the code was supposed to do.  Thanks,

**Comment by alandmoore** [comment]
This has been an ongoing bug in PyQt5, which I believe has been addressed in newer versions of PyQt5.  See https://stackoverflow.com/a/59126660/1454109 for more details.
